name: Android CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Replace ENV
      env:
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: |
        sed -i '/^RELEASE_STORE_PASSWORD/d' gradle.properties
        sed -i '/^RELEASE_KEY_ALIAS/d' gradle.properties
        sed -i '/^RELEASE_KEY_PASSWORD/d' gradle.properties
        
        echo -e "RELEASE_STORE_PASSWORD=${RELEASE_KEY_PASSWORD}" >> gradle.properties
        echo -e "RELEASE_KEY_ALIAS=${RELEASE_KEY_ALIAS}" >> gradle.properties
        echo -e "RELEASE_KEY_PASSWORD=${RELEASE_KEY_PASSWORD}" >> gradle.properties
    - name: Build with Gradle
      run: |
        # ./gradlew clean && ./gradlew build
        # echo -e '\n\n\nBuild success\n\n\n'
        ./gradlew clean && ./gradlew assembleRelease
        echo -e '\n\n\nRelease Success\n\n\n'
        ls ./app/build/outputs/apk/release
    - uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: ./app/build/outputs/apk/release/app-release.apk
