name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v4
    - name: Build Release
      env:
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: |
        find . -type f -name "*.gradle.kts" -exec sed -i '/aliyun/d' {} +
        find . -type f -name "*.gradle.kts" -exec sed -i '/tencent/d' {} +
        find . -name 'gradle-wrapper.properties' -exec sed -i 's/mirrors\.cloud\.tencent\.com\/gradle/services.gradle.org\/distributions/g' {} +
        chmod +x ./gradlew
        ./gradlew assembleRelease -P RELEASE_STORE_PASSWORD=${RELEASE_KEY_PASSWORD} -P RELEASE_KEY_ALIAS=${RELEASE_KEY_ALIAS} -P RELEASE_KEY_PASSWORD=${RELEASE_KEY_PASSWORD}
    - uses: actions/upload-artifact@v4
      with:
        name: ScanQRCode-Release-APK.zip
        path: ./app/build/outputs/apk/release/*.apk
    - uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: ./app/build/outputs/apk/release/*.apk
        draft: true